FROM golang:1.6.3-alpine 

MAINTAINER Zheng Liu zliu@dataman-inc.com

RUN mkdir /go-jobs

ADD bin/swan /go-jobs/swan
ADD swagger-ui-2.2.8 /go-jobs/swagger-ui-2.2.8

WORKDIR /go-jobs

EXPOSE 9999

ENTRYPOINT ["./swan"]
