FROM demoregistry.dataman-inc.com/library/centos7-base:latest

MAINTAINER Zheng Liu zliu@dataman-inc.com

RUN mkdir /go-swan

ADD bin/swan /go-swan/swan
ADD swagger-ui-2.2.8 /go-swan/swagger-ui-2.2.8

WORKDIR /go-swan

EXPOSE 9999

ENTRYPOINT ["./swan --enable-dns --enable-proxy"]
