// Code generated by protoc-gen-gogo.
// source: application.proto
// DO NOT EDIT!

/*
	Package types is a generated protocol buffer package.

	It is generated from these files:
		application.proto
		health.proto
		raft.proto
		task.proto
		update.proto
		version.proto

	It has these top-level messages:
		Application
		HealthCheck
		Command
		InternalRaftRequest
		StoreAction
		Framework
		Task
		PortMappings
		UpdatePolicy
		Version
		Container
		Docker
		Parameter
		PortMapping
		Volume
		KillPolicy
*/
package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// skipping weak import gogoproto "gogoproto"

import strings "strings"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
import sort "sort"
import strconv "strconv"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Application struct {
	ID                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Instances         uint64 `protobuf:"varint,3,opt,name=instances,proto3" json:"instances,omitempty"`
	UpdatedInstances  uint64 `protobuf:"varint,4,opt,name=updatedInstances,proto3" json:"updatedInstances,omitempty"`
	RunningInstances  uint64 `protobuf:"varint,5,opt,name=runningInstances,proto3" json:"runningInstances,omitempty"`
	RollbackInstances uint64 `protobuf:"varint,6,opt,name=rollbackInstances,proto3" json:"rollbackInstances,omitempty"`
	RunAs             string `protobuf:"bytes,7,opt,name=runAs,proto3" json:"runAs,omitempty"`
	ClusterId         string `protobuf:"bytes,8,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
	Status            string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Created           int64  `protobuf:"varint,10,opt,name=created,proto3" json:"created,omitempty"`
	Updated           int64  `protobuf:"varint,11,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptorApplication, []int{0} }

func init() {
	proto.RegisterType((*Application)(nil), "types.Application")
}
func (this *Application) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Application)
	if !ok {
		that2, ok := that.(Application)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Application")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Application but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Application but is not nil && this == nil")
	}
	if this.ID != that1.ID {
		return fmt.Errorf("ID this(%v) Not Equal that(%v)", this.ID, that1.ID)
	}
	if this.Name != that1.Name {
		return fmt.Errorf("Name this(%v) Not Equal that(%v)", this.Name, that1.Name)
	}
	if this.Instances != that1.Instances {
		return fmt.Errorf("Instances this(%v) Not Equal that(%v)", this.Instances, that1.Instances)
	}
	if this.UpdatedInstances != that1.UpdatedInstances {
		return fmt.Errorf("UpdatedInstances this(%v) Not Equal that(%v)", this.UpdatedInstances, that1.UpdatedInstances)
	}
	if this.RunningInstances != that1.RunningInstances {
		return fmt.Errorf("RunningInstances this(%v) Not Equal that(%v)", this.RunningInstances, that1.RunningInstances)
	}
	if this.RollbackInstances != that1.RollbackInstances {
		return fmt.Errorf("RollbackInstances this(%v) Not Equal that(%v)", this.RollbackInstances, that1.RollbackInstances)
	}
	if this.RunAs != that1.RunAs {
		return fmt.Errorf("RunAs this(%v) Not Equal that(%v)", this.RunAs, that1.RunAs)
	}
	if this.ClusterId != that1.ClusterId {
		return fmt.Errorf("ClusterId this(%v) Not Equal that(%v)", this.ClusterId, that1.ClusterId)
	}
	if this.Status != that1.Status {
		return fmt.Errorf("Status this(%v) Not Equal that(%v)", this.Status, that1.Status)
	}
	if this.Created != that1.Created {
		return fmt.Errorf("Created this(%v) Not Equal that(%v)", this.Created, that1.Created)
	}
	if this.Updated != that1.Updated {
		return fmt.Errorf("Updated this(%v) Not Equal that(%v)", this.Updated, that1.Updated)
	}
	return nil
}
func (this *Application) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Application)
	if !ok {
		that2, ok := that.(Application)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Instances != that1.Instances {
		return false
	}
	if this.UpdatedInstances != that1.UpdatedInstances {
		return false
	}
	if this.RunningInstances != that1.RunningInstances {
		return false
	}
	if this.RollbackInstances != that1.RollbackInstances {
		return false
	}
	if this.RunAs != that1.RunAs {
		return false
	}
	if this.ClusterId != that1.ClusterId {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.Created != that1.Created {
		return false
	}
	if this.Updated != that1.Updated {
		return false
	}
	return true
}
func (this *Application) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 15)
	s = append(s, "&types.Application{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Instances: "+fmt.Sprintf("%#v", this.Instances)+",\n")
	s = append(s, "UpdatedInstances: "+fmt.Sprintf("%#v", this.UpdatedInstances)+",\n")
	s = append(s, "RunningInstances: "+fmt.Sprintf("%#v", this.RunningInstances)+",\n")
	s = append(s, "RollbackInstances: "+fmt.Sprintf("%#v", this.RollbackInstances)+",\n")
	s = append(s, "RunAs: "+fmt.Sprintf("%#v", this.RunAs)+",\n")
	s = append(s, "ClusterId: "+fmt.Sprintf("%#v", this.ClusterId)+",\n")
	s = append(s, "Status: "+fmt.Sprintf("%#v", this.Status)+",\n")
	s = append(s, "Created: "+fmt.Sprintf("%#v", this.Created)+",\n")
	s = append(s, "Updated: "+fmt.Sprintf("%#v", this.Updated)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringApplication(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func extensionToGoStringApplication(m github_com_gogo_protobuf_proto.Message) string {
	e := github_com_gogo_protobuf_proto.GetUnsafeExtensionsMap(m)
	if e == nil {
		return "nil"
	}
	s := "proto.NewUnsafeXXX_InternalExtensions(map[int32]proto.Extension{"
	keys := make([]int, 0, len(e))
	for k := range e {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)
	ss := []string{}
	for _, k := range keys {
		ss = append(ss, strconv.Itoa(k)+": "+e[int32(k)].GoString())
	}
	s += strings.Join(ss, ",") + "})"
	return s
}
func (m *Application) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Application) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApplication(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApplication(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Instances != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintApplication(dAtA, i, uint64(m.Instances))
	}
	if m.UpdatedInstances != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintApplication(dAtA, i, uint64(m.UpdatedInstances))
	}
	if m.RunningInstances != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintApplication(dAtA, i, uint64(m.RunningInstances))
	}
	if m.RollbackInstances != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintApplication(dAtA, i, uint64(m.RollbackInstances))
	}
	if len(m.RunAs) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintApplication(dAtA, i, uint64(len(m.RunAs)))
		i += copy(dAtA[i:], m.RunAs)
	}
	if len(m.ClusterId) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintApplication(dAtA, i, uint64(len(m.ClusterId)))
		i += copy(dAtA[i:], m.ClusterId)
	}
	if len(m.Status) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintApplication(dAtA, i, uint64(len(m.Status)))
		i += copy(dAtA[i:], m.Status)
	}
	if m.Created != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintApplication(dAtA, i, uint64(m.Created))
	}
	if m.Updated != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintApplication(dAtA, i, uint64(m.Updated))
	}
	return i, nil
}

func encodeFixed64Application(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Application(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintApplication(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedApplication(r randyApplication, easy bool) *Application {
	this := &Application{}
	this.ID = string(randStringApplication(r))
	this.Name = string(randStringApplication(r))
	this.Instances = uint64(uint64(r.Uint32()))
	this.UpdatedInstances = uint64(uint64(r.Uint32()))
	this.RunningInstances = uint64(uint64(r.Uint32()))
	this.RollbackInstances = uint64(uint64(r.Uint32()))
	this.RunAs = string(randStringApplication(r))
	this.ClusterId = string(randStringApplication(r))
	this.Status = string(randStringApplication(r))
	this.Created = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Created *= -1
	}
	this.Updated = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Updated *= -1
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyApplication interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneApplication(r randyApplication) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringApplication(r randyApplication) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneApplication(r)
	}
	return string(tmps)
}
func randUnrecognizedApplication(r randyApplication, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldApplication(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldApplication(dAtA []byte, r randyApplication, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateApplication(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateApplication(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateApplication(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateApplication(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateApplication(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateApplication(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateApplication(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Application) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovApplication(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovApplication(uint64(l))
	}
	if m.Instances != 0 {
		n += 1 + sovApplication(uint64(m.Instances))
	}
	if m.UpdatedInstances != 0 {
		n += 1 + sovApplication(uint64(m.UpdatedInstances))
	}
	if m.RunningInstances != 0 {
		n += 1 + sovApplication(uint64(m.RunningInstances))
	}
	if m.RollbackInstances != 0 {
		n += 1 + sovApplication(uint64(m.RollbackInstances))
	}
	l = len(m.RunAs)
	if l > 0 {
		n += 1 + l + sovApplication(uint64(l))
	}
	l = len(m.ClusterId)
	if l > 0 {
		n += 1 + l + sovApplication(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovApplication(uint64(l))
	}
	if m.Created != 0 {
		n += 1 + sovApplication(uint64(m.Created))
	}
	if m.Updated != 0 {
		n += 1 + sovApplication(uint64(m.Updated))
	}
	return n
}

func sovApplication(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozApplication(x uint64) (n int) {
	return sovApplication(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Application) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApplication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Application: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Application: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplication
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplication
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instances", wireType)
			}
			m.Instances = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Instances |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedInstances", wireType)
			}
			m.UpdatedInstances = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedInstances |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunningInstances", wireType)
			}
			m.RunningInstances = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RunningInstances |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollbackInstances", wireType)
			}
			m.RollbackInstances = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RollbackInstances |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunAs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplication
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RunAs = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplication
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApplication
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			m.Created = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Created |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Updated", wireType)
			}
			m.Updated = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Updated |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApplication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApplication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApplication(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApplication
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApplication
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthApplication
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowApplication
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipApplication(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthApplication = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApplication   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("application.proto", fileDescriptorApplication) }

var fileDescriptorApplication = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4e, 0x83, 0x40,
	0x14, 0x86, 0x0b, 0x05, 0x2a, 0xaf, 0x1b, 0x3b, 0x69, 0xcc, 0xc4, 0x18, 0x34, 0xc6, 0x85, 0x31,
	0x46, 0x17, 0x9e, 0xa0, 0x8d, 0x1b, 0xb6, 0xac, 0xdc, 0x4e, 0x61, 0x42, 0x88, 0x38, 0x43, 0x98,
	0x61, 0xe1, 0x8d, 0x3c, 0x82, 0x47, 0xe8, 0xd2, 0x0b, 0x68, 0xda, 0x9e, 0xc0, 0xa5, 0x4b, 0xdf,
	0x0c, 0xe8, 0x24, 0xed, 0xe2, 0x4f, 0xde, 0xff, 0x7f, 0xff, 0x23, 0x0f, 0x80, 0x19, 0x6b, 0x9a,
	0xba, 0xca, 0x99, 0xae, 0xa4, 0xb8, 0x6b, 0x5a, 0xa9, 0x25, 0x09, 0xf5, 0x6b, 0xc3, 0xd5, 0xe9,
	0xbc, 0x94, 0xa5, 0xb4, 0xc9, 0xbd, 0x99, 0x7a, 0x78, 0xf9, 0xe9, 0xc3, 0x74, 0xe1, 0x56, 0xc8,
	0x09, 0xf8, 0x55, 0x41, 0xbd, 0x0b, 0xef, 0x3a, 0x5e, 0x46, 0xbb, 0xaf, 0x73, 0x3f, 0x7d, 0xcc,
	0x30, 0x21, 0x04, 0x02, 0xc1, 0x5e, 0x38, 0xf5, 0x0d, 0xc9, 0xec, 0x4c, 0xce, 0x20, 0xae, 0x84,
	0xd2, 0x4c, 0xe4, 0x5c, 0xd1, 0x31, 0x82, 0x20, 0x73, 0x01, 0xb9, 0x81, 0xe3, 0xae, 0x29, 0x98,
	0xe6, 0x45, 0xfa, 0x5f, 0x0a, 0x6c, 0xe9, 0x20, 0x37, 0xdd, 0xb6, 0x13, 0xa2, 0x12, 0xa5, 0xeb,
	0x86, 0x7d, 0x77, 0x3f, 0x27, 0xb7, 0x30, 0x6b, 0x65, 0x5d, 0xaf, 0x58, 0xfe, 0xec, 0xca, 0x91,
	0x2d, 0x1f, 0x02, 0x32, 0x87, 0x10, 0x9f, 0xb0, 0x50, 0x74, 0x62, 0x0f, 0xef, 0x8d, 0xb9, 0x3c,
	0xaf, 0x3b, 0xa5, 0x79, 0x9b, 0x16, 0xf4, 0xc8, 0x12, 0x17, 0xe0, 0x37, 0x88, 0x70, 0x5d, 0x77,
	0x8a, 0xc6, 0x16, 0x0d, 0x8e, 0x50, 0x98, 0xe4, 0x2d, 0x37, 0x97, 0x53, 0x40, 0x30, 0xce, 0xfe,
	0xac, 0x21, 0xc3, 0x3b, 0xd1, 0x69, 0x4f, 0x06, 0xbb, 0xbc, 0x5a, 0x6f, 0x93, 0xd1, 0x66, 0x9b,
	0x78, 0xdf, 0xa8, 0x1f, 0xd4, 0xdb, 0x2e, 0xf1, 0xde, 0x51, 0x6b, 0xd4, 0x07, 0x6a, 0x83, 0x7a,
	0x1a, 0xad, 0x22, 0xfb, 0x3b, 0x1e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xf2, 0x90, 0x46,
	0xc0, 0x01, 0x00, 0x00,
}
