// Code generated by protoc-gen-gogo.
// source: version.proto
// DO NOT EDIT!

package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// skipping weak import gogoproto "gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Version struct {
	ID           string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId        string            `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Command      string            `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Cpus         float64           `protobuf:"fixed64,4,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Mem          float64           `protobuf:"fixed64,5,opt,name=mem,proto3" json:"mem,omitempty"`
	Disk         float64           `protobuf:"fixed64,6,opt,name=disk,proto3" json:"disk,omitempty"`
	Instances    int32             `protobuf:"varint,7,opt,name=instances,proto3" json:"instances,omitempty"`
	RunAs        string            `protobuf:"bytes,8,opt,name=runAs,proto3" json:"runAs,omitempty"`
	Container    *Container        `protobuf:"bytes,9,opt,name=container" json:"container,omitempty"`
	Labels       map[string]string `protobuf:"bytes,10,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HealthChecks []*HealthCheck    `protobuf:"bytes,11,rep,name=healthChecks" json:"healthChecks,omitempty"`
	Env          map[string]string `protobuf:"bytes,12,rep,name=env" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	KillPolicy   *KillPolicy       `protobuf:"bytes,13,opt,name=killPolicy" json:"killPolicy,omitempty"`
	UpdatePolicy *UpdatePolicy     `protobuf:"bytes,14,opt,name=updatePolicy" json:"updatePolicy,omitempty"`
	Constraints  []string          `protobuf:"bytes,15,rep,name=constraints" json:"constraints,omitempty"`
	Uris         []string          `protobuf:"bytes,16,rep,name=uris" json:"uris,omitempty"`
	Ip           []string          `protobuf:"bytes,15,rep,name=ip" json:"ip,omitempty"`
	Mode         string            `protobuf:"bytes,16,opt,name=mode,proto3" json:"mode,omitempty"`
}
